INSERT INTO `xslt_versions` (
  `xslt_id`,`version`,`description`,`last_modified_by`,`last_modified_time`,`xslt_path`,`xslt_location`,`originating_bundle`)
VALUES
  ('candidates_export_tee_pfl_snippet_boolean', 0,'Initial TEE Query for Candidate Export (Retrieve Candidate Custom Snippet for Boolean)' ,'ttc_verify',NOW(),'/artifacts/tee_default_candidate_export_pfl_snippet_boolean.xml', 0,'com.talemetry.verify.serviceprovider.talemetryapigateway'),
  ('candidates_export_tee_pfl_snippet_date',    0,'Initial TEE Query for Candidate Export (Retrieve Candidate Custom Snippet for Date)'    ,'ttc_verify',NOW(),'/artifacts/tee_default_candidate_export_pfl_snippet_date.xml',    0,'com.talemetry.verify.serviceprovider.talemetryapigateway'),
  ('candidates_export_tee_pfl_snippet_datetime',0,'Initial TEE Query for Candidate Export (Retrieve Candidate Custom Snippet for Datetime)','ttc_verify',NOW(),'/artifacts/tee_default_candidate_export_pfl_snippet_datetime.xml',0,'com.talemetry.verify.serviceprovider.talemetryapigateway'),
  ('candidates_export_tee_pfl_snippet_string',  0,'Initial TEE Query for Candidate Export (Retrieve Candidate Custom Snippet for String)'  ,'ttc_verify',NOW(),'/artifacts/tee_default_candidate_export_pfl_snippet_string.xml',  0,'com.talemetry.verify.serviceprovider.talemetryapigateway'),
  ('jobs_export_tee_pfl_snippet_boolean',       0,'Initial TEE Query for Job Export (Retrieve Requisition Custom Snippet for Boolean)' ,    'ttc_verify',NOW(),'/artifacts/tee_default_job_export_pfl_snippet_boolean.xml',       0,'com.talemetry.verify.serviceprovider.talemetryapigateway'),
  ('jobs_export_tee_pfl_snippet_date',          0,'Initial TEE Query for Job Export (Retrieve Requisition Custom Snippet for Date)'    ,    'ttc_verify',NOW(),'/artifacts/tee_default_job_export_pfl_snippet_date.xml',          0,'com.talemetry.verify.serviceprovider.talemetryapigateway'),
  ('jobs_export_tee_pfl_snippet_datetime',      0,'Initial TEE Query for Job Export (Retrieve Requisition Custom Snippet for Datetime)',    'ttc_verify',NOW(),'/artifacts/tee_default_job_export_pfl_snippet_datetime.xml',      0,'com.talemetry.verify.serviceprovider.talemetryapigateway'),
  ('jobs_export_tee_pfl_snippet_string',        0,'Initial TEE Query for Job Export (Retrieve Requisition Custom Snippet for String)'  ,    'ttc_verify',NOW(),'/artifacts/tee_default_job_export_pfl_snippet_string.xml',        0,'com.talemetry.verify.serviceprovider.talemetryapigateway');
