ALTER TABLE `q_processing` ADD COLUMN `id` INT NOT NULL AUTO_INCREMENT  AFTER `payload_hrnx_pii` 
, ADD UNIQUE INDEX `txn_id_UNIQUE` (`txn_id` ASC) 
, DROP PRIMARY KEY 
, ADD PRIMARY KEY (`id`) ;

ALTER TABLE `q_incoming` DROP COLUMN `source` , DROP COLUMN `version` , ADD COLUMN `id` INT NOT NULL AUTO_INCREMENT  FIRST 
, ADD PRIMARY KEY (`id`) ;

ALTER TABLE `q_sent` ADD COLUMN `id` INT NOT NULL AUTO_INCREMENT  FIRST 
, ADD PRIMARY KEY (`id`) ;
