ALTER TABLE `q_processing` ADD COLUMN `REQUESTOR_ID` VARCHAR(45) NULL DEFAULT NULL  AFTER `id` ;
ALTER TABLE `q_incoming` ADD COLUMN `REQUESTOR_ID` VARCHAR(45) NULL DEFAULT NULL  AFTER `payload_hrnx_pii` ;
