CALL VerifyEZService('ttc_api_gateway', 'purge_candidates', 'integration', 'Candidates Purge', 'ttc_api_gateway_api', '');

INSERT INTO `field_mappings` (
   `service_tp_id`
  ,`service_id`
  ,`field_id`
  ,`client_group_id`
  ,`client_user_id`
  ,`field_state`
  ,`field_display`
  ,`field_sensitivity`
  ,`field_cp_state`
  ,`field_cp_display`
  ,`field_cp_sensitivity`
  ,`enabled`
  ,`field_group`
  ,`field_order`
  ,`field_default`
  ,`created_date`
  ,`created_tp_id`
  ,`created_tp_user_id`
  ,`updated_date`
  ,`updated_tp_id`
  ,`updated_tp_user_id`
) VALUES (
   'ttc_api_gateway'
  ,'purge_candidates'
  ,'integration_attachment_id'
  ,''
  ,''
  ,1
  ,0
  ,1
  ,1
  ,0
  ,1
  ,1
  ,400
  ,100
  ,''
  ,NOW()
  ,'ttc_verify'
  ,'ttc_verify'
  ,NOW()
  ,'ttc_verify'
  ,'ttc_verify'
),(
   'ttc_api_gateway'
  ,'purge_candidates'
  ,'integration_external_id_template'
  ,''
  ,''
  ,1
  ,0
  ,1
  ,1
  ,0
  ,1
  ,1
  ,400
  ,100
  ,''
  ,NOW()
  ,'ttc_verify'
  ,'ttc_verify'
  ,NOW()
  ,'ttc_verify'
  ,'ttc_verify'
),(
   'ttc_api_gateway'
  ,'purge_candidates'
  ,'integration_target_excluded_qualifier'
  ,''
  ,''
  ,1
  ,0
  ,1
  ,1
  ,0
  ,1
  ,1
  ,400
  ,100
  ,''
  ,NOW()
  ,'ttc_verify'
  ,'ttc_verify'
  ,NOW()
  ,'ttc_verify'
  ,'ttc_verify'
),(
   'ttc_api_gateway'
  ,'purge_candidates'
  ,'integration_target_allowed_source'
  ,''
  ,''
  ,1
  ,0
  ,1
  ,1
  ,0
  ,1
  ,1
  ,400
  ,100
  ,''
  ,NOW()
  ,'ttc_verify'
  ,'ttc_verify'
  ,NOW()
  ,'ttc_verify'
  ,'ttc_verify'
),(
   'ttc_api_gateway'
  ,'purge_candidates'
  ,'integration_target_included_qualifier'
  ,''
  ,''
  ,1
  ,0
  ,1
  ,1
  ,0
  ,1
  ,1
  ,400
  ,100
  ,''
  ,NOW()
  ,'ttc_verify'
  ,'ttc_verify'
  ,NOW()
  ,'ttc_verify'
  ,'ttc_verify'
);
UPDATE `service_mappings` SET `service_select`='0' WHERE `client_group_id`='' and`client_user_id`='' and`package_id`='ttc_api_gateway_api' and`service_tp_id`='ttc_api_gateway' and`service_id`='purge_candidates';
